[CmdletBinding()]
param(
    [switch]$CheckOnly,
    [switch]$SkipInstall,
    [switch]$NoBrowser
)

$ErrorActionPreference = "Stop"

function Write-Section([string]$Text) {
    Write-Host ""
    Write-Host "=== $Text ===" -ForegroundColor Cyan
}

function Test-Import([string]$PythonExe, [string]$ModuleName) {
    & $PythonExe -c "import $ModuleName" 2>$null
    return $LASTEXITCODE -eq 0
}

function Test-ListeningPort([int]$Port) {
    return [bool](Get-NetTCPConnection -State Listen -LocalPort $Port -ErrorAction SilentlyContinue)
}

function Read-LocalEnv([string]$Path) {
    if (-not (Test-Path -LiteralPath $Path)) {
        return
    }

    foreach ($line in Get-Content -LiteralPath $Path) {
        if ($line -match '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$') {
            $name = $Matches[1]
            $value = $Matches[2]
            if ($value.Length -ge 2 -and $value.StartsWith('"') -and $value.EndsWith('"')) {
                $value = $value.Substring(1, $value.Length - 2)
            }
            Set-Item -Path "Env:$name" -Value $value
        }
    }
}

function Resolve-LocalPath([string]$Value, [string]$RootPath) {
    if (-not $Value) {
        return $Value
    }
    if (-not (Test-IsLocalPathReference $Value)) {
        return $Value
    }
    if ([System.IO.Path]::IsPathRooted($Value)) {
        return $Value
    }
    return [System.IO.Path]::GetFullPath((Join-Path $RootPath $Value))
}

function Test-IsLocalPathReference([string]$Value) {
    if (-not $Value) {
        return $false
    }
    return (
        [System.IO.Path]::IsPathRooted($Value) -or
        $Value.StartsWith(".\") -or
        $Value.StartsWith("./") -or
        $Value.StartsWith("..\") -or
        $Value.StartsWith("../") -or
        $Value.Contains("\") -or
        (Test-Path -LiteralPath $Value)
    )
}

$Root = [System.IO.Path]::GetFullPath($PSScriptRoot)
$FrontendRoot = Join-Path $Root "final-main"
$FrontendApp = Join-Path $FrontendRoot "apps\main-platform"
$Requirements = Join-Path $Root "requirements.txt"
$LocalEnv = Join-Path $Root "backend.local.env"
$FrontendEnv = Join-Path $FrontendApp ".env.local"

Write-Section "Locate project"
Write-Host "Project root: $Root"

if (-not (Test-Path -LiteralPath (Join-Path $Root "node_server.py"))) {
    throw "node_server.py was not found beside this launcher."
}
if (-not (Test-Path -LiteralPath $Requirements)) {
    throw "requirements.txt was not found beside this launcher."
}
if (-not (Test-Path -LiteralPath (Join-Path $FrontendRoot "package.json"))) {
    throw "final-main/package.json was not found beside this launcher."
}

Read-LocalEnv $LocalEnv

$PythonCommand = Get-Command python.exe -ErrorAction SilentlyContinue
if (-not $PythonCommand) {
    $PythonCommand = Get-Command py.exe -ErrorAction SilentlyContinue
}
if (-not $PythonCommand) {
    throw "Python was not found. Install Python 3.11+ and enable it in PATH."
}
$PythonExe = $PythonCommand.Source

$PnpmCommand = Get-Command pnpm.cmd -ErrorAction SilentlyContinue
if (-not $PnpmCommand) {
    $PnpmCommand = Get-Command pnpm.exe -ErrorAction SilentlyContinue
}
if (-not $PnpmCommand) {
    throw "pnpm was not found. Install Node.js and pnpm, then reopen Explorer."
}
$PnpmExe = $PnpmCommand.Source

Write-Host "Python: $PythonExe"
Write-Host "pnpm:   $PnpmExe"

# Local defaults are intentionally relative to this project, never to a user-specific path.
$env:FEDERATION_INTERNAL_TOKEN = if ($env:FEDERATION_INTERNAL_TOKEN) { $env:FEDERATION_INTERNAL_TOKEN } else { "mia-federation-internal-token-2024" }
$env:JWT_SECRET_KEY = if ($env:JWT_SECRET_KEY) { $env:JWT_SECRET_KEY } else { "local-dev-jwt-secret-change-me" }
$env:FEDERATION_SM4_KEY = if ($env:FEDERATION_SM4_KEY) { $env:FEDERATION_SM4_KEY } else { "mia-sm4-key-2024" }
$env:FEDERATION_ALLOW_HTTP_LOCALHOST = "true"

$miaModelCandidate = Join-Path $Root "models\MiA-Emb-8B"
$baseModelCandidate = Join-Path $Root "models\Qwen3-Embedding-8B"
if (-not $env:MODEL_PATH -and (Test-Path -LiteralPath $miaModelCandidate)) {
    $env:MODEL_PATH = $miaModelCandidate
}
if (-not $env:BASE_MODEL_PATH -and (Test-Path -LiteralPath $baseModelCandidate)) {
    $env:BASE_MODEL_PATH = $baseModelCandidate
}
if (-not $env:MODEL_PATH) {
    $env:MODEL_PATH = "MindscapeRAG/MiA-Emb-8B"
}
if (-not $env:BASE_MODEL_PATH) {
    $env:BASE_MODEL_PATH = "Qwen/Qwen3-Embedding-8B"
}
if ($env:MODEL_PATH) {
    $env:MODEL_PATH = Resolve-LocalPath $env:MODEL_PATH $Root
}
if ($env:BASE_MODEL_PATH) {
    $env:BASE_MODEL_PATH = Resolve-LocalPath $env:BASE_MODEL_PATH $Root
}

$frontendEnvContent = @"
# Generated by start-local.bat. Paths are local to the current machine.
NEXT_PUBLIC_MIA_RAG_AUTH_URL=http://127.0.0.1:6006
MIA_RAG_NODE_URL=http://127.0.0.1:6006
FEDERATION_INTERNAL_TOKEN=$($env:FEDERATION_INTERNAL_TOKEN)
FEDERATION_ALLOW_HTTP_LOCALHOST=true
"@
Set-Content -LiteralPath $FrontendEnv -Value $frontendEnvContent -Encoding utf8

if (Test-IsLocalPathReference $env:MODEL_PATH -and -not (Test-Path -LiteralPath $env:MODEL_PATH)) {
    throw "MODEL_PATH does not exist: $env:MODEL_PATH"
}
if (Test-IsLocalPathReference $env:BASE_MODEL_PATH -and -not (Test-Path -LiteralPath $env:BASE_MODEL_PATH)) {
    throw "BASE_MODEL_PATH does not exist: $env:BASE_MODEL_PATH"
}
if (-not (Test-IsLocalPathReference $env:MODEL_PATH) -or -not (Test-IsLocalPathReference $env:BASE_MODEL_PATH)) {
    Write-Host "Model repositories will be downloaded automatically on first backend start." -ForegroundColor Yellow
}

Write-Section "Check Python dependencies"
$requiredImports = @("sqlalchemy", "fastapi", "uvicorn", "torch", "transformers")
$missingImports = @($requiredImports | Where-Object { -not (Test-Import $PythonExe $_) })

if ($missingImports.Count -gt 0) {
    Write-Host "Missing Python packages: $($missingImports -join ', ')" -ForegroundColor Yellow
    if ($SkipInstall) {
        throw "Dependencies are missing and -SkipInstall was supplied."
    }
    Write-Host "Installing requirements.txt. This can take a while on the first run..."
    & $PythonExe -m pip install -r $Requirements
    if ($LASTEXITCODE -ne 0) {
        throw "Python dependency installation failed."
    }
}

if (-not (Test-Import $PythonExe "lightrag")) {
    if ($SkipInstall) {
        throw "lightrag is missing and -SkipInstall was supplied."
    }
    $vendoredLightRag = Join-Path $Root "LightRAG"
    if (Test-Path -LiteralPath $vendoredLightRag) {
        Write-Host "Installing local LightRAG package..."
        & $PythonExe -m pip install -e $vendoredLightRag
    } else {
        Write-Host "Installing lightrag-hku..."
        & $PythonExe -m pip install lightrag-hku
    }
    if ($LASTEXITCODE -ne 0) {
        throw "LightRAG dependency installation failed."
    }
}

Write-Section "Check frontend dependencies"
if (-not (Test-Path -LiteralPath (Join-Path $FrontendRoot "node_modules"))) {
    if ($SkipInstall) {
        throw "Frontend node_modules is missing and -SkipInstall was supplied."
    }
    Write-Host "Installing frontend dependencies. This can take a while on the first run..."
    & $PnpmExe install --dir $FrontendRoot
    if ($LASTEXITCODE -ne 0) {
        throw "Frontend dependency installation failed."
    }
}

if ($CheckOnly) {
    Write-Host ""
    Write-Host "Local configuration check passed." -ForegroundColor Green
    exit 0
}

Write-Section "Start backend services"
$backendCommand = "& '$PythonExe' -m api.main --host 0.0.0.0 --port 6006"
$nodeCommand = "& '$PythonExe' node_server.py --host 0.0.0.0 --port 6008"

if (-not (Test-ListeningPort 6006)) {
    Start-Process -FilePath "powershell.exe" `
        -WorkingDirectory $Root `
        -ArgumentList @("-NoExit", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", $backendCommand)
    Write-Host "Started API server on http://127.0.0.1:6006"
} else {
    Write-Host "API port 6006 is already in use; leaving the existing service running."
}

if (-not (Test-ListeningPort 6008)) {
    Start-Process -FilePath "powershell.exe" `
        -WorkingDirectory $Root `
        -ArgumentList @("-NoExit", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", $nodeCommand)
    Write-Host "Started node server on http://127.0.0.1:6008"
} else {
    Write-Host "Node port 6008 is already in use; leaving the existing service running."
}

Write-Section "Start frontend"
if (-not (Test-ListeningPort 3000)) {
    $frontendCommand = "& '$PnpmExe' dev"
    Start-Process -FilePath "powershell.exe" `
        -WorkingDirectory $FrontendRoot `
        -ArgumentList @("-NoExit", "-NoProfile", "-ExecutionPolicy", "Bypass", "-Command", $frontendCommand)
    Write-Host "Started frontend on http://127.0.0.1:3000"
} else {
    Write-Host "Frontend port 3000 is already in use; leaving the existing frontend running."
}

if (-not $NoBrowser) {
    Start-Sleep -Seconds 3
    Start-Process "http://127.0.0.1:3000"
}

Write-Host ""
Write-Host "Startup commands dispatched. Keep the backend and frontend windows open." -ForegroundColor Green
